export const SOCKET_IO_PROXYFIED = false; 
export const FILE_SERVER_PROXYFIED = false;
export const SOCKET_IO_PORT_FROM_SERVER = 8686; 
export const SOCKET_IO_PORT_FROM_CLIENT = 8686; 
export const FILE_SERVER_PORT_FROM_CLIENT = 8687;
export const FILE_SERVER_PORT_FROM_SERVER = 8687;
export const HOST = 'sk.kortas.fr'; 
//export const RESULTS_DIR = "/RUNS";
export const RESULTS_DIR = "/scratch/project/k1477/sam/RUNS";
// export const RESULTS_DIR = "/home/kortass/WWW/wrfweb/exports/RUNS";
export const OIL_SERVER_WORKING_DIR = "/home/kortass/WWW/wrfweb/OIL/";
export const OIL_WORKING_DIR = "/home/kortass/WWW/wrfweb/OIL/";
export const OIL_RESULTS_DIR = "/datawaha/ecrc/kortass/IGULF/OIL";
export const DATAWAHA_RESULTS_DIR = "/datawaha/ecrc/kortass/IGULF/";
// export const OIL_SPILL_EXECUTABLE = "/datawaha/ecrc/kortass/IGULF/SOFTS/MEDSLIK/SCRIPTS/run.sh";

export const OIL_SPILL_EXECUTABLE = "/datawaha/ecrc/kortass/IGULF/SOFTS/MEDSLIK/SCRIPTS/run.sh";
export const OIL_SPILL_INSTALL = "/datawaha/ecrc/kortass/IGULF/SOFTS/MEDSLIK/";
export const OIL_SPILL_VISU = "/datawaha/ecrc/kortass/IGULF/SOFTS/MEDSLIK/SCRIPTS/visualize/";
