#!/usr/bin/expect -f
#
# This Expect script was generated by autoexpect on Wed Nov 18 03:31:51 2020
# Expect and autoexpect were both written by Don Libes, NIST.
#
# Note that autoexpect does not guarantee a working script.  It
# necessarily has to guess about certain things.  Two reasons a script
# might fail are:
#
# 1) timing - A surprising number of programs (rn, ksh, zsh, telnet,
# etc.) and devices discard or ignore keystrokes that arrive "too
# quickly" after prompts.  If you find your new script hanging up at
# one spot, try adding a short sleep just before the previous send.
# Setting "force_conservative" to 1 (see below) makes Expect do this
# automatically - pausing briefly before sending each character.  This
# pacifies every program I know of.  The -c flag makes the script do
# this in the first place.  The -C flag allows you to define a
# character to toggle this mode off and on.

set force_conservative 0  ;# set to 1 to force conservative mode even if
			  ;# script wasn't run conservatively originally
if {$force_conservative} {
	set send_slow {1 .1}
	proc send {ignore arg} {
		sleep .1
		exp_send -s -- $arg
	}
}

#
# 2) differing output - Some programs produce different output each time
# they run.  The "date" command is an obvious example.  Another is
# ftp, if it produces throughput statistics at the end of a file
# transfer.  If this causes a problem, delete these patterns or replace
# them with wildcards.  An alternative is to use the -p flag (for
# "prompt") which makes Expect only look for the last line of output
# (i.e., the prompt).  The -P flag allows you to define a character to
# toggle this mode off and on.
#
# Read the man page for more info.
#
# -Don


set timeout -1
spawn amplify publish
match_max 100000
send -- "\r"
expect -exact "Are you sure you want to continue?\[22m\[0m \[0m\[2m(Y/n) \[22m\[43D\[43C"
send -- "\r"
expect -exact "Do you want to generate code for your newly created GraphQL API\[22m\[0m \[0m\[2m(Y/n) \[22m\[72D\[72C"
send -- "\r"
expect -exact "\[2K\[G\[32m?\[39m \[1mDo you want to generate code for your newly created GraphQL API\[22m\[0m \[0m\[36mYes\[39m\[69D\[69C\r
\[?25l\[32m?\[39m \[1mChoose the code generation language target\[22m\[0m \[0m\[2m(Use arrow keys)\[22m\r
\[36m❯ javascript\[39m \r
  typescript \r
  flow \[7D\[7C"
send -- "\r"
expect -exact "\[2K\[1A\[2K\[1A\[2K\[1A\[2K\[G\[32m?\[39m \[1mChoose the code generation language target\[22m\[0m \[0m\[36mjavascript\[39m\[55D\[55C\r
\[?25h\[32m?\[39m \[1mEnter the file name pattern of graphql queries, mutations and subscriptions\[22m\[0m \[0m\[2m(src/graphql/**/*.js) \[22m\[100D\[100C"
send -- "\r"
expect -exact "\[2K\[G\[32m?\[39m \[1mEnter the file name pattern of graphql queries, mutations and subscriptions\[22m\[0m \[0m\[36msrc/graphql/**/*.js\[39m\[97D\[97C\r
\[32m?\[39m \[1mDo you want to generate/update all possible GraphQL operations - queries, mutations and subscriptions\r
\[22m\[0m \[0m\[2m(Y/n) \[22m\[7D\[7C"
send -- "\r"
expect -exact "\[2K\[1A\[2K\[G\[32m?\[39m \[1mDo you want to generate/update all possible GraphQL operations - queries, mutations and subscriptions\r
\[22m\[0m \[0m\[36mYes\[39m\[4D\[4C\r
\[32m?\[39m \[1mEnter maximum statement depth \[increase from default if your schema is deeply nested\]\[22m\[0m \[0m\[2m(2) \[22m\[92D\[92C"
send -- "\r"
expect eof
