#!/usr/bin/expect -f
#
# This Expect script was generated by autoexpect on Wed Nov 18 03:03:10 2020
# Expect and autoexpect were both written by Don Libes, NIST.
#
# Note that autoexpect does not guarantee a working script.  It
# necessarily has to guess about certain things.  Two reasons a script
# might fail are:
#
# 1) timing - A surprising number of programs (rn, ksh, zsh, telnet,
# etc.) and devices discard or ignore keystrokes that arrive "too
# quickly" after prompts.  If you find your new script hanging up at
# one spot, try adding a short sleep just before the previous send.
# Setting "force_conservative" to 1 (see below) makes Expect do this
# automatically - pausing briefly before sending each character.  This
# pacifies every program I know of.  The -c flag makes the script do
# this in the first place.  The -C flag allows you to define a
# character to toggle this mode off and on.

set force_conservative 0  ;# set to 1 to force conservative mode even if
			  ;# script wasn't run conservatively originally
if {$force_conservative} {
	set send_slow {1 .1}
	proc send {ignore arg} {
		sleep .1
		exp_send -s -- $arg
	}
}

#
# 2) differing output - Some programs produce different output each time
# they run.  The "date" command is an obvious example.  Another is
# ftp, if it produces throughput statistics at the end of a file
# transfer.  If this causes a problem, delete these patterns or replace
# them with wildcards.  An alternative is to use the -p flag (for
# "prompt") which makes Expect only look for the last line of output
# (i.e., the prompt).  The -P flag allows you to define a character to
# toggle this mode off and on.
#
# Read the man page for more info.
#
# -Don


set timeout -1
spawn amplify add api
match_max 100000
send -- "\r"
expect -exact "\r
\[?25l\[32m?\[39m \[1mPlease select from one of the below mentioned services:\[22m\[0m \[0m\[2m(Use arrow keys)\[22m\r
\[36m❯ GraphQL\[39m \r
  REST \[7D\[7C\[2K\[1A\[2K\[1A\[2K\[G\[32m?\[39m \[1mPlease select from one of the below mentioned services:\[22m\[0m \[0m\[36mGraphQL\[39m\[65D\[65C\r
\[?25h\[32m?\[39m \[1mProvide API name:\[22m\[0m \[0m\[2m(ludionexpect) \[22m\[35D\[35C"
send -- "\r"
expect -exact "\[2K\[G\[32m?\[39m \[1mProvide API name:\[22m\[0m \[0m\[36mludionexpect\[39m\[32D\[32C\r
\[?25l\[32m?\[39m \[1mChoose the default authorization type for the API\[22m\[0m \[0m\[2m(Use arrow keys)\[22m\r
\[36m❯ API key\[39m \r
  Amazon Cognito User Pool \r
  IAM \r
  OpenID Connect \[17D\[17C"
send -- "\r"
expect -exact "\[2K\[1A\[2K\[1A\[2K\[1A\[2K\[1A\[2K\[G\[32m?\[39m \[1mChoose the default authorization type for the API\[22m\[0m \[0m\[36mAPI key\[39m\[59D\[59C\r
\[?25h\[32m?\[39m \[1mEnter a description for the API key:\[22m\[0m \[0m\[39D\[39C"
send -- "l"
expect -exact "\[2K\[G\[32m?\[39m \[1mEnter a description for the API key:\[22m\[0m \[0ml\[40D\[40C"
send -- "u"
expect -exact "\[2K\[G\[32m?\[39m \[1mEnter a description for the API key:\[22m\[0m \[0mlu\[41D\[41C"
send -- "d"
expect -exact "\[2K\[G\[32m?\[39m \[1mEnter a description for the API key:\[22m\[0m \[0mlud\[42D\[42C"
send -- "i"
expect -exact "\[2K\[G\[32m?\[39m \[1mEnter a description for the API key:\[22m\[0m \[0mludi\[43D\[43C"
send -- "o"
expect -exact "\[2K\[G\[32m?\[39m \[1mEnter a description for the API key:\[22m\[0m \[0mludio\[44D\[44C"
send -- "n"
expect -exact "\[2K\[G\[32m?\[39m \[1mEnter a description for the API key:\[22m\[0m \[0mludion\[45D\[45C"
send -- " "
expect -exact "\[2K\[G\[32m?\[39m \[1mEnter a description for the API key:\[22m\[0m \[0mludion \[46D\[46C"
send -- "e"
expect -exact "\[2K\[G\[32m?\[39m \[1mEnter a description for the API key:\[22m\[0m \[0mludion e\[47D\[47C"
send -- "x"
expect -exact "\[2K\[G\[32m?\[39m \[1mEnter a description for the API key:\[22m\[0m \[0mludion ex\[48D\[48C"
send -- "p"
expect -exact "\[2K\[G\[32m?\[39m \[1mEnter a description for the API key:\[22m\[0m \[0mludion exp\[49D\[49C"
send -- "e"
expect -exact "\[2K\[G\[32m?\[39m \[1mEnter a description for the API key:\[22m\[0m \[0mludion expe\[50D\[50C"
send -- "c"
expect -exact "\[2K\[G\[32m?\[39m \[1mEnter a description for the API key:\[22m\[0m \[0mludion expec\[51D\[51C"
send -- "t"
expect -exact "\[2K\[G\[32m?\[39m \[1mEnter a description for the API key:\[22m\[0m \[0mludion expect\[52D\[52C"
send -- "\r"
expect -exact "\[2K\[G\[32m?\[39m \[1mEnter a description for the API key:\[22m\[0m \[0m\[36mludion expect\[39m\[52D\[52C\r
\[32m?\[39m \[1mAfter how many days from now the API key should expire (1-365):\[22m\[0m \[0m\[2m(7) \[22m\[70D\[70C"
send -- "3"
expect -exact "\[2K\[G\[32m?\[39m \[1mAfter how many days from now the API key should expire (1-365):\[22m\[0m \[0m3\[67D\[67C"
send -- "6"
expect -exact "\[2K\[G\[32m?\[39m \[1mAfter how many days from now the API key should expire (1-365):\[22m\[0m \[0m36\[68D\[68C"
send -- "5"
expect -exact "\[2K\[G\[32m?\[39m \[1mAfter how many days from now the API key should expire (1-365):\[22m\[0m \[0m365\[69D\[69C"
send -- "\r"
expect -exact "\[2K\[G\[32m?\[39m \[1mAfter how many days from now the API key should expire (1-365):\[22m\[0m \[0m\[36m365\[39m\[69D\[69C\r
\[?25l\[32m?\[39m \[1mDo you want to configure advanced settings for the GraphQL API\[22m\[0m \[0m\[2m(Use arrow keys)\[22m\r
\[36m❯ No, I am done.\[39m \r
  Yes, I want to make some additional changes. \[47D\[47C"
send -- "\r"
expect -exact "\[2K\[1A\[2K\[1A\[2K\[G\[32m?\[39m \[1mDo you want to configure advanced settings for the GraphQL API\[22m\[0m \[0m\[36mNo, I am done.\[39m\[79D\[79C\r
\[?25h\[32m?\[39m \[1mDo you have an annotated GraphQL schema?\[22m\[0m \[0m\[2m(y/N) \[22m\[49D\[49C"
send -- "y"
expect -exact "\[2K\[G\[32m?\[39m \[1mDo you have an annotated GraphQL schema?\[22m\[0m \[0m\[2m(y/N) \[22my\[50D\[50C"
send -- "\r"
expect -exact "\[2K\[G\[32m?\[39m \[1mDo you have an annotated GraphQL schema?\[22m\[0m \[0m\[36mYes\[39m\[46D\[46C\r
\[32m?\[39m \[1mProvide your schema file path:\[22m\[0m \[0m\[33D\[33C"
send -- "a"
expect -exact "\[2K\[G\[32m?\[39m \[1mProvide your schema file path:\[22m\[0m \[0ma\[34D\[34C"
send -- "m"
expect -exact "\[2K\[G\[32m?\[39m \[1mProvide your schema file path:\[22m\[0m \[0mam\[35D\[35C"
send -- "p"
expect -exact "\[2K\[G\[32m?\[39m \[1mProvide your schema file path:\[22m\[0m \[0mamp\[36D\[36C"
send -- "l"
expect -exact "\[2K\[G\[32m?\[39m \[1mProvide your schema file path:\[22m\[0m \[0mampl\[37D\[37C"
send -- "i"
expect -exact "\[2K\[G\[32m?\[39m \[1mProvide your schema file path:\[22m\[0m \[0mampli\[38D\[38C"
send -- "f"
expect -exact "\[2K\[G\[32m?\[39m \[1mProvide your schema file path:\[22m\[0m \[0mamplif\[39D\[39C"
send -- "y"
expect -exact "\[2K\[G\[32m?\[39m \[1mProvide your schema file path:\[22m\[0m \[0mamplify\[40D\[40C"
send -- "_"
expect -exact "\[2K\[G\[32m?\[39m \[1mProvide your schema file path:\[22m\[0m \[0mamplify_\[41D\[41C"
send -- "s"
expect -exact "\[2K\[G\[32m?\[39m \[1mProvide your schema file path:\[22m\[0m \[0mamplify_s\[42D\[42C"
send -- "c"
expect -exact "\[2K\[G\[32m?\[39m \[1mProvide your schema file path:\[22m\[0m \[0mamplify_sc\[43D\[43C"
send -- "h"
expect -exact "\[2K\[G\[32m?\[39m \[1mProvide your schema file path:\[22m\[0m \[0mamplify_sch\[44D\[44C"
send -- "e"
expect -exact "\[2K\[G\[32m?\[39m \[1mProvide your schema file path:\[22m\[0m \[0mamplify_sche\[45D\[45C"
send -- "m"
expect -exact "\[2K\[G\[32m?\[39m \[1mProvide your schema file path:\[22m\[0m \[0mamplify_schem\[46D\[46C"
send -- "a"
expect -exact "\[2K\[G\[32m?\[39m \[1mProvide your schema file path:\[22m\[0m \[0mamplify_schema\[47D\[47C"
send -- "/"
expect -exact "\[2K\[G\[32m?\[39m \[1mProvide your schema file path:\[22m\[0m \[0mamplify_schema/\[48D\[48C"
send -- "s"
expect -exact "\[2K\[G\[32m?\[39m \[1mProvide your schema file path:\[22m\[0m \[0mamplify_schema/s\[49D\[49C"
send -- "c"
expect -exact "\[2K\[G\[32m?\[39m \[1mProvide your schema file path:\[22m\[0m \[0mamplify_schema/sc\[50D\[50C"
send -- "h"
expect -exact "\[2K\[G\[32m?\[39m \[1mProvide your schema file path:\[22m\[0m \[0mamplify_schema/sch\[51D\[51C"
send -- "e"
expect -exact "\[2K\[G\[32m?\[39m \[1mProvide your schema file path:\[22m\[0m \[0mamplify_schema/sche\[52D\[52C"
send -- "m"
expect -exact "\[2K\[G\[32m?\[39m \[1mProvide your schema file path:\[22m\[0m \[0mamplify_schema/schem\[53D\[53C"
send -- "a"
expect -exact "\[2K\[G\[32m?\[39m \[1mProvide your schema file path:\[22m\[0m \[0mamplify_schema/schema\[54D\[54C"
send -- "."
expect -exact "\[2K\[G\[32m?\[39m \[1mProvide your schema file path:\[22m\[0m \[0mamplify_schema/schema.\[55D\[55C"
send -- "g"
expect -exact "\[2K\[G\[32m?\[39m \[1mProvide your schema file path:\[22m\[0m \[0mamplify_schema/schema.g\[56D\[56C"
send -- "r"
expect -exact "\[2K\[G\[32m?\[39m \[1mProvide your schema file path:\[22m\[0m \[0mamplify_schema/schema.gr\[57D\[57C"
send -- "a"
expect -exact "\[2K\[G\[32m?\[39m \[1mProvide your schema file path:\[22m\[0m \[0mamplify_schema/schema.gra\[58D\[58C"
send -- "p"
expect -exact "\[2K\[G\[32m?\[39m \[1mProvide your schema file path:\[22m\[0m \[0mamplify_schema/schema.grap\[59D\[59C"
send -- "h"
expect -exact "\[2K\[G\[32m?\[39m \[1mProvide your schema file path:\[22m\[0m \[0mamplify_schema/schema.graph\[60D\[60C"
send -- "q"
expect -exact "\[2K\[G\[32m?\[39m \[1mProvide your schema file path:\[22m\[0m \[0mamplify_schema/schema.graphq\[61D\[61C"
send -- "l"
expect -exact "\[2K\[G\[32m?\[39m \[1mProvide your schema file path:\[22m\[0m \[0mamplify_schema/schema.graphql\[62D\[62C"
send -- "\r"
expect eof
