#!/usr/bin/expect -f
#
# This Expect script was generated by autoexpect on Wed Nov 18 03:06:05 2020
# Expect and autoexpect were both written by Don Libes, NIST.
#
# Note that autoexpect does not guarantee a working script.  It
# necessarily has to guess about certain things.  Two reasons a script
# might fail are:
#
# 1) timing - A surprising number of programs (rn, ksh, zsh, telnet,
# etc.) and devices discard or ignore keystrokes that arrive "too
# quickly" after prompts.  If you find your new script hanging up at
# one spot, try adding a short sleep just before the previous send.
# Setting "force_conservative" to 1 (see below) makes Expect do this
# automatically - pausing briefly before sending each character.  This
# pacifies every program I know of.  The -c flag makes the script do
# this in the first place.  The -C flag allows you to define a
# character to toggle this mode off and on.

set force_conservative 0  ;# set to 1 to force conservative mode even if
			  ;# script wasn't run conservatively originally
if {$force_conservative} {
	set send_slow {1 .1}
	proc send {ignore arg} {
		sleep .1
		exp_send -s -- $arg
	}
}

#
# 2) differing output - Some programs produce different output each time
# they run.  The "date" command is an obvious example.  Another is
# ftp, if it produces throughput statistics at the end of a file
# transfer.  If this causes a problem, delete these patterns or replace
# them with wildcards.  An alternative is to use the -p flag (for
# "prompt") which makes Expect only look for the last line of output
# (i.e., the prompt).  The -P flag allows you to define a character to
# toggle this mode off and on.
#
# Read the man page for more info.
#
# -Don


set timeout -1
spawn amplify add auth
match_max 100000
send -- "\r"
expect -exact "\r
\[0mUsing service: Cognito, provided by: awscloudformation\[0m\r
\[?25l \[32m\[39m\r
\[32m The current configured provider is Amazon Cognito. \[39m\r
\[32m\[39m \r
 \[1mDo you want to use the default authentication and security configuration?\[22m\[0m \[0m\[2m(Use arrow keys)\[22m\r
\[36m❯ Default configuration\[39m \r
  Default configuration with Social Provider (Federation) \r
  Manual configuration \r
  I want to learn more. \[24D\[24C\[2K\[1A\[2K\[1A\[2K\[1A\[2K\[1A\[2K\[1A\[2K\[1A\[2K\[1A\[2K\[G \[32m\[39m\r
\[32m The current configured provider is Amazon Cognito. \[39m\r
\[32m\[39m \r
 \[1mDo you want to use the default authentication and security configuration?\[22m\[0m \[0m\[36mDefault configuration\[39m\[96D\[96C\r
\[?25h\[?25l \[31mWarning: you will not be able to edit these selections.\[39m \r
 \[1mHow do you want users to be able to sign in?\[22m\[0m \[0m\[2m(Use arrow keys)\[22m\r
\[36m❯ Username\[39m \r
  Email \r
  Phone Number \r
  Email or Phone Number \r
  I want to learn more. \[24D\[24C"
send -- "\r"
expect -exact "\[2K\[1A\[2K\[1A\[2K\[1A\[2K\[1A\[2K\[1A\[2K\[1A\[2K\[G \[31mWarning: you will not be able to edit these selections.\[39m \r
 \[1mHow do you want users to be able to sign in?\[22m\[0m \[0m\[36mUsername\[39m\[54D\[54C\r
\[?25h\[?25l \[1mDo you want to configure advanced settings?\[22m\[0m \[0m\[2m(Use arrow keys)\[22m\r
\[36m❯ No, I am done.\[39m \r
  Yes, I want to make some additional changes. \[47D\[47C"
send -- "\r"
expect eof
